[package]
name = "scu"
version = "1.3.4"
edition = "2021"

[profile.release]
strip = true
lto = true

[dependencies]
regex-lite = { version = "0.1.5" }
libscu = { version = "1.3.6", features = ["full"] }