[package]
name = "scu"
version = "1.5.0"
edition = "2021"

[profile.release]
strip = true
lto = true

[dependencies]
regex-lite = { version = "0.1.5" }
libscu = { version = "2.0.0", features = ["full"] }
