[package]
name = "scu"
version = "1.4.0"
edition = "2021"

[profile.release]
strip = true
lto = true

[dependencies]
regex-lite = { version = "0.1.5" }
libscu = { git = "https://github.com/omnitix/libscu", version = "1.3.6", features = ["full"] }